### ISSUE TITLE
Turn off semantic tokens or change their behaviour through config.

### ISSUE THREAD

**Issue by Jacob-Flasheye** [rcjsuen/dockerfile-language-server#264]
Hi.

I like this language server a lot, except for the semantic highlighting (when using Neovim).
In particular, the semantic tokens overwrite the highlighting on bash commands, which I don't like, as it removes most highlighting in the bash commands.
I'm no expert on language servers, but my best guess is that I can change the priority of the highlights in Neovim, but until I learn how to do that I would like to know if there is some setting that will turn off semantic tokens for this language server?

**Comment by rcjsuen** [comment]
@Jacob-Flasheye According to the documentation [here](https://neovim.io/doc/user/lsp.html#_lua-module:-vim.lsp.semantic_tokens), you can opt out of semantic highlighting if you wish. Putting the following code in my `init.lua` seemed to do the trick for me. I hope this helps!

```Lua
require("lspconfig").dockerls.setup({
  on_attach = function(client, bufnr)
    -- Opt out of semantic token highlighting
    client.server_capabilities.semanticTokensProvider = nil
  end
})
```
