### ISSUE TITLE
Question about repo name

### ISSUE THREAD

**Issue by chenrui333** [rcjsuen/dockerfile-language-server#268]
👋 I have a quick question while reviewing [a homebrew PR](https://github.com/Homebrew/homebrew-core/pull/152763). 

Consider there is no other LSP for dockerfile, why not use dockerfile-language-server for the repo name then? (the binary might be good to rename from `docker-langserver` to `docker-language-server`, but that is less an issue IMO)

**Comment by rcjsuen** [comment]
@chenrui333 Yes, the name of the repository is/was poorly named in hindsight. I have not had a pressing reason to update it.

**Comment by chenrui333** [comment]
@rcjsuen thanks for the reply, maybe take advantage of this packaging opportunity to do the repo name change if you dont have big concerns? :)

**Comment by rcjsuen** [comment]
The repository has been renamed. Thank you for bringing this up, @chenrui333.
