### ISSUE TITLE
Evaluate variable default values in determining if blank

### ISSUE THREAD

**Issue by duckbrain** [rcjsuen/dockerfile-language-server#269]
If I create a Dockerfile with the following contents

```Dockerfile
FROM ${VAR:-ignore}
```

I get a diagnostic error:

```
dockerfile-utils: base name (${VAR:-ignore}) should not be blank [51]
```

The `:-` syntax provides a default value so if `$VAR` is blank, `ignore` is used instead, so there's no way for the image name to be blank.

**Comment by rcjsuen** [comment]
@duckbrain Thank you for bringing this to our attention. I have opened https://github.com/rcjsuen/dockerfile-utils/issues/126 to track this.

**Comment by rcjsuen** [comment]
@duckbrain Thanks again for the bug report. The latest 0.13.0 release of the language server should not flag this as an error anymore.
